### ISSUE TITLE
No DAs scraped for Brisbane in the last week

### ISSUE THREAD

**Issue by katska** [planningalerts-scrapers/issues#445] opened 2021-10-06 02:54 UTC
Someone reported 
" Read more information" however the opening website does not open.

The extension is:
http://pdonline.brisbane.qld.gov.au/MasterView/modules/applicationmaster/default.aspx?page=wrapper&key=A003410384

I tried to following links to this DA, but it hangs, ie. the page doesn't load. I wonder if Brisbane City Council have removed public access to their internal system and public access only via development.i system now? Or has it just moved?

0 new applications scraped03 Oct – 10 Oct 2021
https://www.planningalerts.org.au/authorities/brisbane

**Comment by mlandauer** [comment] 2022-06-20 01:33
Duplicate of #449

**Closed as completed by mlandauer** 2022-06-20 01:33 UTC
