### ISSUE TITLE
Inner West not finding DAs

### ISSUE THREAD

**Issue by katska** [planningalerts-scrapers/issues#812] opened 2023-08-17 05:34 UTC
Shows finding no new DAs[ under the hood](https://www.planningalerts.org.au/authorities/inner_west/under_the_hood)
Looking at morph output there's a bug: 

https://morph.io/planningalerts-scrapers/multiple_cianywhere/

 inner_west: ERROR: Unable to find css ".tile"
 /app/vendor/bundle/ruby/2.5.0/gems/capybara-3.35.3/lib/capybara/node/finders.rb:303:in `block in synced_resolve'

**Comment by mlandauer** [comment] 2023-09-11 06:51
Duplicate of #813

**Closed as completed by mlandauer** 2023-09-11 06:51 UTC
Labels: ci-anywhere
