### ISSUE TITLE
Newcastle has moved to T1Cloud

### ISSUE THREAD

**Issue by jamezpolley** [planningalerts-scrapers/issues#11] opened 2020-03-12 04:12 UTC
New landing page is at https://cn-web.t1cloud.com/T1PRDefault/WebApps/eProperty/P1/eTrack/eTrackApplicationSearch.aspx?r=TCON.LG.WEBGUEST&f=%24P1.ETR.SEARCH.ENQ

ATDIS url is currently unknown - council is looking for it for us.

If there's no ATDIS on the t1cloud we may have to revert to the T1 scraper

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2kidh)

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2x8xx)

**Comment by mlandauer** [comment] 2020-07-13 02:09
Newcastle is currently working on getting their ATDIS feed working again. I'll leave this issue open until that gets resolved.

**Comment by mlandauer** [comment] 2020-07-27 01:34
Duplicate of #83

**Closed by mlandauer** 2020-07-27 01:34 UTC
Labels: ATDIS
